/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import LogicMain.DatabaseHandler;
import LogicMain.Student;

/**
 *
 * @author maxaj
 */
public class NewStudentScreen extends javax.swing.JFrame {

    /**
     * Creates new form CreateNewScreen_
     */
    private StudentScreen SS;
    private Student newStudent;
    private DatabaseHandler dataCur = new DatabaseHandler();
    private final int value = 3;
    private HelpScreen SIHS;

    public NewStudentScreen(StudentScreen inSS) {
        //creates the JFrame and populates it with content
        initComponents();
        //Sets the location of the JFrame to the centre of the screen
        setLocationRelativeTo(null);
        lbl_Warning1.setVisible(false);
        lbl_Warning2.setVisible(false);
        lbl_Warning3.setVisible(false);
        lbl_Warning4.setVisible(false);
        SS = inSS;
    }
    //Takes inputted values and construcs a new student object, returning a true/false value
    public boolean GetStudentInfo() {
        String FName = txtfld_Name.getText();
        String LName = txtfld_Surname.getText();
        int Age = 0;

        switch (cmb_Grade.getSelectedIndex()) {
            case 0:
                Age = 14;
                break;
            case 1:
                Age = 15;
                break;
            case 2:
                Age = 16;
                break;
            case 3:
                Age = 17;
                break;
            case 4:
                Age = 18;
                break;
            default:
                System.out.println("ERROR - No Age Selected");

        }

        newStudent = new Student(0, FName, LName, Age, 0);

        return ValidateData(FName, LName);
    }
    
    //Validates the inputted data before saving, returns a true/false value
    private Boolean ValidateData(String inFName, String inSName) {
        boolean valid = true;
        lbl_Warning1.setVisible(false);
        lbl_Warning2.setVisible(false);
        lbl_Warning3.setVisible(false);
        lbl_Warning4.setVisible(false);

        if (inFName.isEmpty()) {
            lbl_Warning3.setVisible(true);
            valid = false;

        } else {

            lbl_Warning3.setVisible(false);

        }

        for (int i = 0; i < inFName.length(); i++) {
            if (Character.isAlphabetic(inFName.charAt(i))) {
                lbl_Warning1.setVisible(false);

            } else {
                valid = false;
                lbl_Warning1.setVisible(true);
                break;
            }

        }

        if (inSName.isEmpty()) {
            lbl_Warning4.setVisible(true);
            valid = false;

        } else {

            lbl_Warning4.setVisible(false);

            for (int i = 0; i < inSName.length(); i++) {
                if (Character.isAlphabetic(inSName.charAt(i))) {
                    lbl_Warning2.setVisible(false);

                } else {
                    valid = false;
                    lbl_Warning2.setVisible(true);
                    break;
                }

            }
        }

        return valid;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Surname = new javax.swing.JLabel();
        lbl_AgeGroup = new javax.swing.JLabel();
        btn_Help = new javax.swing.JButton();
        lbl_Heading = new javax.swing.JLabel();
        logo_SideDecor = new javax.swing.JLabel();
        txtfld_Name = new javax.swing.JTextField();
        txtfld_Surname = new javax.swing.JTextField();
        cmb_Grade = new javax.swing.JComboBox<>();
        btn_Cancel = new javax.swing.JButton();
        btn_Create = new javax.swing.JButton();
        lbl_Name = new javax.swing.JLabel();
        lbl_Warning1 = new javax.swing.JLabel();
        lbl_Warning2 = new javax.swing.JLabel();
        lbl_Warning3 = new javax.swing.JLabel();
        lbl_Warning4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Surname.setText("Surname:");

        lbl_AgeGroup.setText("Age Group:");

        btn_Help.setText("?");
        btn_Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HelpActionPerformed(evt);
            }
        });

        lbl_Heading.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_Heading.setText("Create Student");

        logo_SideDecor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lib/CornerDecalsSmall.png"))); // NOI18N

        txtfld_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld_NameActionPerformed(evt);
            }
        });

        cmb_Grade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "u14", "u15", "u16", "u17", "u18" }));
        cmb_Grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_GradeActionPerformed(evt);
            }
        });

        btn_Cancel.setText("Cancel");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });

        btn_Create.setText("Create");
        btn_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CreateActionPerformed(evt);
            }
        });

        lbl_Name.setText("Name:");

        lbl_Warning1.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Warning1.setText("Alphabetical characters only");

        lbl_Warning2.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Warning2.setText("Alphabetical characters only");

        lbl_Warning3.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Warning3.setText("Field is empty");

        lbl_Warning4.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Warning4.setText("Field is empty");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbl_Heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo_SideDecor))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Help, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_AgeGroup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_Grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lbl_Name)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Surname)
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Warning4)
                    .addComponent(lbl_Warning3)
                    .addComponent(lbl_Warning2)
                    .addComponent(lbl_Warning1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtfld_Name)
                        .addComponent(txtfld_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logo_SideDecor)
                    .addComponent(lbl_Heading))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfld_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Warning1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Warning3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfld_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Surname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Warning2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Warning4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_AgeGroup))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btn_Help)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Opens Help Screen
    private void btn_HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HelpActionPerformed
        // open help screen
        SIHS = new HelpScreen(value);
        SIHS.setVisible(true);

    }//GEN-LAST:event_btn_HelpActionPerformed
    
    
    private void txtfld_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld_NameActionPerformed
    //Goes back to Student Screen
    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        // go back to database access screen

        SS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_CancelActionPerformed
    //Takes inputted values and inserts new student object int the database
    private void btn_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CreateActionPerformed
        // save and go to database access screen

        if (GetStudentInfo()) {
            dataCur.insertStudent(newStudent);

            SS.StudentScreenPopulate();
            System.out.println(newStudent.toString());

            SS.setVisible(true);
            this.setVisible(false);

        } else {

        }


    }//GEN-LAST:event_btn_CreateActionPerformed

    private void cmb_GradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_GradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_GradeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewStudentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewStudentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewStudentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewStudentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewStudentScreen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Create;
    private javax.swing.JButton btn_Help;
    private javax.swing.JComboBox<String> cmb_Grade;
    private javax.swing.JLabel lbl_AgeGroup;
    private javax.swing.JLabel lbl_Heading;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_Surname;
    private javax.swing.JLabel lbl_Warning1;
    private javax.swing.JLabel lbl_Warning2;
    private javax.swing.JLabel lbl_Warning3;
    private javax.swing.JLabel lbl_Warning4;
    private javax.swing.JLabel logo_SideDecor;
    private javax.swing.JTextField txtfld_Name;
    private javax.swing.JTextField txtfld_Surname;
    // End of variables declaration//GEN-END:variables
}
