/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import LogicMain.DatabaseHandler;
import LogicMain.Race;
import LogicMain.Student;
import java.util.Calendar;
import javax.swing.DefaultListModel;

/**
 *
 * @author maxaj
 */
public class RaceScreen extends javax.swing.JFrame {

    //Creates a new database handeler instance
    DatabaseHandler db = new DatabaseHandler();

    /**
     * Creates new form RaceScreen
     */
    private ChoiceScreen CS;
    private RaceDetailsScreen RDS;
    private RaceAddScreen RAS;
    private final int value = 6;
    private HelpScreen SIHS;

    public RaceScreen(ChoiceScreen inCS) {

        initComponents();
        //creates the JFrame and populates it with content

        setLocationRelativeTo(null);

        //Sets the location of the JFrame to the centre of the screen
        CS = inCS;

        RaceScreenPopulate();
    }

    //Populates the screen using the Races database
    public void RaceScreenPopulate() {
        Race[] allRaces = db.getAllRaces();
        DefaultListModel l = new DefaultListModel();
        for (int x = 0; x < allRaces.length; x++) {
            l.addElement(allRaces[x]);

        }
        lst_Students.setModel(l);

    }
//Failed attempt at making a search function :(
//    public void RaceSearchPopulate() {
//
//        Calendar cal = Calendar.getInstance();
//
//        if (txtfld_Year.getText().equals("") || txtfld_Month.getText().equals("") || txtfld_Day.getText().equals("")) {
//
//            cal = Calendar.getInstance();
//
//        } else {
//            cal.set(Integer.parseInt(txtfld_Year.getText()), Integer.parseInt(txtfld_Month.getText()), Integer.parseInt(txtfld_Day.getText()));
//
//        }
//
//        int dist;
//
//        if (txtfld_Distance.getText().equals("")) {
//            dist = 0;
//
//        } else {
//            dist = Integer.parseInt(txtfld_Distance.getText());
//
//        }
//        System.out.println(dist + " " + cal);
//
//        if (dist != 0 && cal != Calendar.getInstance()) {
//            System.out.println("1");
//
//            Race[] allRaces = db.searchRaces(dist, cal);
//            DefaultListModel l = new DefaultListModel();
//            for (int x = 0; x < allRaces.length; x++) {
//                l.addElement(allRaces[x]);
//
//            }
//            lst_Students.setModel(l);
//
//        } else if (dist == 0 && cal != Calendar.getInstance()) {
//            System.out.println("2");
//            Race[] allRaces = db.searchRaces(cal);
//
//            DefaultListModel l = new DefaultListModel();
//            for (int x = 0; x < allRaces.length; x++) {
//                l.addElement(allRaces[x]);
//
//            }
//            lst_Students.setModel(l);
//
//        } else if (dist != 0 && cal == Calendar.getInstance()) {
//            System.out.println("3");
//            Race[] allRaces = db.searchRaces(dist);
//
//            DefaultListModel l = new DefaultListModel();
//            for (int x = 0; x < allRaces.length; x++) {
//                l.addElement(allRaces[x]);
//
//            }
//            lst_Students.setModel(l);
//
//        } else {
//            RaceScreenPopulate();
//        }
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo_SideDecor = new javax.swing.JLabel();
        btn_CreateNew = new javax.swing.JButton();
        lbl_Students = new javax.swing.JLabel();
        btn_Back = new javax.swing.JButton();
        btn_Help = new javax.swing.JButton();
        scrll_SearchPanel = new javax.swing.JScrollPane();
        lst_Students = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(178, 219, 244));

        logo_SideDecor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lib/CornerDecalsSmall.png"))); // NOI18N

        btn_CreateNew.setText("Create New");
        btn_CreateNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CreateNewActionPerformed(evt);
            }
        });

        lbl_Students.setText("Races");

        btn_Back.setText("Back");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        btn_Help.setText("?");
        btn_Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HelpActionPerformed(evt);
            }
        });

        scrll_SearchPanel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lst_Students.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Mathew Ragland - 8", "Alfred Dunnington -9 ", "Darnell Trail - 12", "Ike Baillargeon - 11", "Chuck Lininger - 9", "Lon Dunmire - 10", "Bill Dillahunt - 8", "Freddy Silvers - 12", "Kevin Chea - 12", "Kirby Achorn - 11", "Riley Croston - 9", "Chauncey Ma - 8", "Marcelino Tompson - 10", "Phillip Sheedy - 11", "Kory Ryals - 8", "Leopoldo Petrin - 9", "Rafael Ritzer - 10", "Delbert Hickey - 12", "Len Carstarphen - 9", "Roger Fresquez" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lst_Students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_StudentsMouseClicked(evt);
            }
        });
        scrll_SearchPanel.setViewportView(lst_Students);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Students)
                .addGap(135, 135, 135)
                .addComponent(logo_SideDecor))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btn_CreateNew))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(155, 155, 155)
                            .addComponent(btn_Back)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Help))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(scrll_SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Students)
                    .addComponent(logo_SideDecor))
                .addGap(40, 40, 40)
                .addComponent(scrll_SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btn_CreateNew)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Back)
                    .addComponent(btn_Help))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Opens the Add Race Screen
    private void btn_CreateNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CreateNewActionPerformed
        // go to create new screen
        RAS = new RaceAddScreen(this);
        RAS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_CreateNewActionPerformed
//Goes back to the Choice Screen
    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        // go back to login screen

        CS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_BackActionPerformed
//Opens the Help Screen
    private void btn_HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HelpActionPerformed
        // go to help screen
        SIHS = new HelpScreen(value);
        SIHS.setVisible(true);
    }//GEN-LAST:event_btn_HelpActionPerformed
//Opens the Race Details Screen
    private void lst_StudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_StudentsMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {

            String value = String.valueOf(lst_Students.getSelectedValue());

            String[] x = value.split(", ");
            int id = Integer.parseInt(x[0]);

            Race sel = db.getRaceFromID(id);

            RDS = new RaceDetailsScreen(this, sel);
            RDS.setVisible(true);
            this.setVisible(false);

        }
    }//GEN-LAST:event_lst_StudentsMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RaceScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RaceScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RaceScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RaceScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RaceScreen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_CreateNew;
    private javax.swing.JButton btn_Help;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Students;
    private javax.swing.JLabel logo_SideDecor;
    private javax.swing.JList<String> lst_Students;
    private javax.swing.JScrollPane scrll_SearchPanel;
    // End of variables declaration//GEN-END:variables
}
