/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import LogicMain.DatabaseHandler;
import LogicMain.Student;

/**
 *
 * @author maxaj
 */
public class StudentDetailScreen extends javax.swing.JFrame {

    /**
     * Creates new form OpenScreen
     */
    private StudentScreen SS;
    private EditStudentScreen ESC;
    private Student selStudent;
    private DatabaseHandler dataCur = new DatabaseHandler();
    private final int value = 2;
    private HelpScreen SIHS;

    public StudentDetailScreen(StudentScreen inSS, Student inSel) {
        //creates the JFrame and populates it with content

        initComponents();

        //Sets the location of the JFrame to the centre of the screen
        setLocationRelativeTo(null);
        SS = inSS;
        selStudent = inSel;
        populateDetails();

    }
    
    //Populates the screen with the selected students details
    public void populateDetails() {

        txtpn_NameHeading.setText(selStudent.getfName() + " " + selStudent.getlName());

        txtpn_RacesComplete.setText(String.valueOf(dataCur.countNumberRaces(selStudent.getId())));
        txtpn_DaysAbsent.setText(String.valueOf(selStudent.getAttend()));
        txtpn_AgeGroup.setText(String.valueOf(selStudent.getAge()));

    }
    
    //Setter method used for setting the student of the screen
    public void SetStudent(Student inStudent) {
        selStudent = inStudent;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_RacesComplete = new javax.swing.JLabel();
        lbl_DaysAbsent = new javax.swing.JLabel();
        lbl_AgeGroup = new javax.swing.JLabel();
        btn_Help = new javax.swing.JButton();
        logo_SideDecor = new javax.swing.JLabel();
        btn_Back = new javax.swing.JButton();
        scrll_RacesComplete = new javax.swing.JScrollPane();
        txtpn_RacesComplete = new javax.swing.JTextPane();
        scrll_DaysAbsent = new javax.swing.JScrollPane();
        txtpn_DaysAbsent = new javax.swing.JTextPane();
        scrll_AgeGroup = new javax.swing.JScrollPane();
        txtpn_AgeGroup = new javax.swing.JTextPane();
        scrll_NameHeading = new javax.swing.JScrollPane();
        txtpn_NameHeading = new javax.swing.JTextPane();
        btn_Edit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(178, 219, 244));
        jPanel1.setPreferredSize(new java.awt.Dimension(337, 300));

        lbl_RacesComplete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_RacesComplete.setText("Races Completed:");

        lbl_DaysAbsent.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_DaysAbsent.setText("Days Absent:");

        lbl_AgeGroup.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_AgeGroup.setText("Age Group:");

        btn_Help.setText("?");
        btn_Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HelpActionPerformed(evt);
            }
        });

        logo_SideDecor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lib/CornerDecalsSmall.png"))); // NOI18N

        btn_Back.setText("Back");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        scrll_RacesComplete.setViewportView(txtpn_RacesComplete);

        scrll_DaysAbsent.setViewportView(txtpn_DaysAbsent);

        scrll_AgeGroup.setViewportView(txtpn_AgeGroup);

        scrll_NameHeading.setViewportView(txtpn_NameHeading);

        btn_Edit.setText("Edit");
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(13, 13, 13)
                            .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Help))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_DaysAbsent)
                                    .addComponent(lbl_AgeGroup))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scrll_DaysAbsent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scrll_AgeGroup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_RacesComplete)
                                .addGap(30, 30, 30)
                                .addComponent(scrll_RacesComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(scrll_NameHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logo_SideDecor))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(logo_SideDecor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrll_NameHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_RacesComplete)
                    .addComponent(scrll_RacesComplete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_DaysAbsent)
                    .addComponent(scrll_DaysAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_AgeGroup)
                    .addComponent(scrll_AgeGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Help)
                    .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Goes back to the Student Screen
    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        // go back to database access screen
        SS.StudentScreenPopulate();
        SS.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_BackActionPerformed
    //Opend the Help Screen
    private void btn_HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HelpActionPerformed
        // go to help screen
        SIHS = new HelpScreen(value);
        SIHS.setVisible(true);


    }//GEN-LAST:event_btn_HelpActionPerformed
    
    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
        ESC = new EditStudentScreen(this, selStudent);
       ESC.setVisible(true);
        this.setVisible(false);;
    }//GEN-LAST:event_btn_EditActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StudentDetailScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StudentDetailScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StudentDetailScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StudentDetailScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StudentDetailScreen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_Help;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_AgeGroup;
    private javax.swing.JLabel lbl_DaysAbsent;
    private javax.swing.JLabel lbl_RacesComplete;
    private javax.swing.JLabel logo_SideDecor;
    private javax.swing.JScrollPane scrll_AgeGroup;
    private javax.swing.JScrollPane scrll_DaysAbsent;
    private javax.swing.JScrollPane scrll_NameHeading;
    private javax.swing.JScrollPane scrll_RacesComplete;
    private javax.swing.JTextPane txtpn_AgeGroup;
    private javax.swing.JTextPane txtpn_DaysAbsent;
    private javax.swing.JTextPane txtpn_NameHeading;
    private javax.swing.JTextPane txtpn_RacesComplete;
    // End of variables declaration//GEN-END:variables
}
