/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

//import LogicMain.ArrayLayer;
import LogicMain.DatabaseHandler;
import LogicMain.Student;
import javax.swing.DefaultListModel;

/**
 *
 * @author maxaj
 */
public class StudentScreen extends javax.swing.JFrame {

    //Creates a new instance of the database handler
    DatabaseHandler db = new DatabaseHandler();

    /**
     * Creates new form DataBaseAccessScreen
     */
    private ChoiceScreen CS;
    private NewStudentScreen NSS;
    private StudentDetailScreen SDS;
    private final int value = 1;
    private HelpScreen SIHS;

    public StudentScreen(ChoiceScreen inCS) {
        //creates the JFrame and populates it with content

        initComponents();

        //Sets the location of the JFrame to the centre of the screen
        setLocationRelativeTo(null);
        CS = inCS;
        StudentScreenPopulate();

    }
    
    //Populates the screen using the Students database 
    public void StudentScreenPopulate() {
        Student[] allStudents = db.getAllStudents();
        DefaultListModel l = new DefaultListModel();
        for (int x = 0; x < allStudents.length; x++) {
            l.addElement(allStudents[x]);

        }
        lst_Students.setModel(l);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Search = new javax.swing.JButton();
        btn_Help = new javax.swing.JButton();
        scrll_SearchPanel = new javax.swing.JScrollPane();
        lst_Students = new javax.swing.JList<>();
        logo_SideDecor = new javax.swing.JLabel();
        lbl_Students = new javax.swing.JLabel();
        btn_Back = new javax.swing.JButton();
        btn_CreateNew1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(178, 219, 244));
        jPanel1.setPreferredSize(new java.awt.Dimension(337, 623));

        btn_Search.setText("Search");

        btn_Help.setText("?");
        btn_Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HelpActionPerformed(evt);
            }
        });

        scrll_SearchPanel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lst_Students.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Mathew Ragland - 8", "Alfred Dunnington -9 ", "Darnell Trail - 12", "Ike Baillargeon - 11", "Chuck Lininger - 9", "Lon Dunmire - 10", "Bill Dillahunt - 8", "Freddy Silvers - 12", "Kevin Chea - 12", "Kirby Achorn - 11", "Riley Croston - 9", "Chauncey Ma - 8", "Marcelino Tompson - 10", "Phillip Sheedy - 11", "Kory Ryals - 8", "Leopoldo Petrin - 9", "Rafael Ritzer - 10", "Delbert Hickey - 12", "Len Carstarphen - 9", "Roger Fresquez" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lst_Students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_StudentsMouseClicked(evt);
            }
        });
        scrll_SearchPanel.setViewportView(lst_Students);

        logo_SideDecor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lib/CornerDecalsSmall.png"))); // NOI18N

        lbl_Students.setText("Students");

        btn_Back.setText("Back");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        btn_CreateNew1.setText("Create New");
        btn_CreateNew1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CreateNew1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(lbl_Students)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(logo_SideDecor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_Back)
                                .addGap(129, 129, 129)
                                .addComponent(btn_Help))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_CreateNew1)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Search)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(scrll_SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo_SideDecor)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Students)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrll_SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Search)
                    .addComponent(btn_CreateNew1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Help)
                    .addComponent(btn_Back))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   //Opens the Student Details Screen
    private void lst_StudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_StudentsMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {

            String value = String.valueOf(lst_Students.getSelectedValue());
            //System.out.println(value);
            String[] x = value.split(", ");
            int id = Integer.parseInt(x[0]);
            System.out.println(id);
            Student sel = db.getStudentFromID(id);
            System.out.println(sel.toString());

            SDS = new StudentDetailScreen(this, sel);
            SDS.setVisible(true);
            this.setVisible(false);

        }
    }//GEN-LAST:event_lst_StudentsMouseClicked

    //Opens the help screen
    private void btn_HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HelpActionPerformed
        // go to help screen
        SIHS = new HelpScreen(value);
        SIHS.setVisible(true);
    }//GEN-LAST:event_btn_HelpActionPerformed
    //Goes Back to Choice Screen
    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        // TODO add your handling code here:
        CS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_BackActionPerformed
    
    //Open New Student Screen
    private void btn_CreateNew1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CreateNew1ActionPerformed
        
        NSS = new NewStudentScreen(this);
        NSS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_CreateNew1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StudentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StudentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StudentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StudentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StudentScreen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_CreateNew1;
    private javax.swing.JButton btn_Help;
    private javax.swing.JButton btn_Search;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Students;
    private javax.swing.JLabel logo_SideDecor;
    private javax.swing.JList<String> lst_Students;
    private javax.swing.JScrollPane scrll_SearchPanel;
    // End of variables declaration//GEN-END:variables
}
